export const paths = Object.freeze({
  login: "/login",
  forgotPassword: "/forgot-password",
  dashboard: "/",
  factories: "/factories",
  machines: "/machines",
  devices: "/devices",
  deviceDetails: "/devices/:deviceId",
  liveMonitoring: "/live-monitoring",
  analytics: "/analytics",
  alerts: "/alerts",
  alertDetails: "/alerts/:alertId",
  reports: "/reports",
  auditLogs: "/audit-logs",
  deviceLogs: "/device-logs",
  notifications: "/notifications",
  securityCenter: "/security-center",
  users: "/users",
  roles: "/roles",
  settings: "/settings",
  profile: "/profile",
  unauthorized: "/unauthorized",
  forbidden: "/forbidden",
});
